# Generated by Django 3.1 on 2021-01-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userstatus', models.IntegerField(default=0, verbose_name='モデルステータス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='D31Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yasumi', models.CharField(default='', max_length=255, verbose_name='希望休')),
                ('month', models.IntegerField(choices=[(0, '--'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=0, verbose_name='月')),
                ('status', models.IntegerField(choices=[(0, '未選択'), (1, '選択中'), (2, '選択済み')], default=0, verbose_name='ステータス')),
                ('form', models.CharField(default='', max_length=10000, verbose_name='フォーム内容')),
                ('table', models.IntegerField(default=0, verbose_name='テーブル優先順位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
    ]
